python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_no_0' --to_detach 'no' --kl_wt 0
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_no_01' --to_detach 'no' --kl_wt 0.1
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_no_001' --to_detach 'no' --kl_wt 0.01
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_no_0001' --to_detach 'no' --kl_wt 0.001
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_no_1' --to_detach 'no' --kl_wt 1
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_yes_0' --to_detach 'yes' --kl_wt 0
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_yes_01' --to_detach 'yes' --kl_wt 0.1
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_yes_001' --to_detach 'yes' --kl_wt 0.01
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_yes_0001' --to_detach 'yes' --kl_wt 0.001
python3 main.py --target 'ad' --max_epoch 1500 --dl_type 'soft_cluster' --data 'office' --num_domain 8 --class_disc 'no' --record_folder 'record_office/idm_yes_1' --to_detach 'yes' --kl_wt 1
