bash ./experiment_do.sh da 1500 0 record_office/dslr_amazon_soft_cluster_8 soft_cluster office 8 no
bash ./experiment_do.sh dw 1500 0 record_office/dslr_webcam_soft_cluster_8 soft_cluster office 8 no
bash ./experiment_do.sh wa 1500 0 record_office/webcam_amazon_soft_cluster_8 soft_cluster office 8 no
bash ./experiment_do.sh wd 1500 0 record_office/webcam_dslr_soft_cluster_8 soft_cluster office 8 no
bash ./experiment_do.sh daw 1500 0 record_office/dslr_amazon_webcam_soft_cluster_8 soft_cluster office 8 no
bash ./experiment_do.sh dwa 1500 0 record_office/dslr_webcam_amazon_soft_cluster_8 soft_cluster office 8 no
bash ./experiment_do.sh wad 1500 0 record_office/webcam_amazon_dslr_soft_cluster_8 soft_cluster office 8 no
bash ./experiment_do.sh ad 1500 0 record_office/amazon_dslr_soft_cluster_6 soft_cluster office 6 no
bash ./experiment_do.sh aw 1500 0 record_office/amazon_webcam_soft_cluster_6 soft_cluster office 6 no
bash ./experiment_do.sh da 1500 0 record_office/dslr_amazon_soft_cluster_6 soft_cluster office 6 no
bash ./experiment_do.sh dw 1500 0 record_office/dslr_webcam_soft_cluster_6 soft_cluster office 6 no
bash ./experiment_do.sh wa 1500 0 record_office/webcam_amazon_soft_cluster_6 soft_cluster office 6 no
bash ./experiment_do.sh wd 1500 0 record_office/webcam_dslr_soft_cluster_6 soft_cluster office 6 no
bash ./experiment_do.sh daw 1500 0 record_office/dslr_amazon_webcam_soft_cluster_6 soft_cluster office 6 no
bash ./experiment_do.sh dwa 1500 0 record_office/dslr_webcam_amazon_soft_cluster_6 soft_cluster office 6 no
bash ./experiment_do.sh wad 1500 0 record_office/webcam_amazon_dslr_soft_cluster_6 soft_cluster office 6 no
