bash ./experiment_do.sh ad 1500 0 record_office/amazon_dslr_source_target source_target office 1 no
bash ./experiment_do.sh aw 1500 0 record_office/amazon_webcam_source_target source_target office 1 no
bash ./experiment_do.sh da 1500 0 record_office/dslr_amazon_source_target source_target office 1 no
bash ./experiment_do.sh dw 1500 0 record_office/dslr_webcam_source_target source_target office 1 no
bash ./experiment_do.sh wa 1500 0 record_office/webcam_amazon_source_target source_target office 1 no
bash ./experiment_do.sh wd 1500 0 record_office/webcam_dslr_source_target source_target office 1 no
bash ./experiment_do.sh daw 1500 0 record_office/dslr_amazon_webcam_source_target source_target office 1 no
bash ./experiment_do.sh dwa 1500 0 record_office/dslr_webcam_amazon_source_target source_target office 1 no
bash ./experiment_do.sh wad 1500 0 record_office/webcam_amazon_dslr_source_target source_target office 1 no
